"""Versioned public command contracts shared by native UI, CLI and MCP.

Inputs: bounded JSON objects. Outputs: JSON schemas and validated domain commands.
No transport, pixels or UI dependencies. IDs refer only to the selected catalog.
Tool annotations describe effects; they never substitute for user authorization.
"""
from .model import LIMITS, Recipe, SYNC_GROUPS, POINT_CURVE_FIELDS, PARAMETRIC_FIELDS, MIXER_FIELDS, BW_FIELDS
from .organization import COLORS, SORTS, FILTER_SCHEMA
from .iptc import SCHEMA as IPTC_SCHEMA
from .metadata_presets import PATCH_SCHEMA as METADATA_PRESET_PATCH

def obj(properties=None, required=()):
    return {'type':'object','properties':properties or {},'required':list(required),'additionalProperties':False}
def integer(lo=0,hi=2**53-1): return {'type':'integer','minimum':lo,'maximum':hi}
def string(maximum=4096): return {'type':'string','minLength':1,'maxLength':maximum}
def array(items,maximum=1000): return {'type':'array','items':items,'maxItems':maximum,'minItems':1}
ID=integer(1); REV=integer(); PATH=string(); BOOL={'type':'boolean'}
OPTIONAL_ID={'anyOf':[ID,{'type':'null'}]}
PATCH={'type':'object','maxProperties':128}
TOOLS={}
def tool(name,description,properties=None,required=(),read=False):
    TOOLS[name]={'name':name,'description':description,'inputSchema':obj(properties,required),
        'annotations':{'readOnlyHint':read,'destructiveHint':False,'idempotentHint':read,'openWorldHint':False}}
tool('service_connection','Inspect engine compatibility or explicitly activate this build when the broker is idle. Preserves pending jobs on a clean handoff; never interrupts active work.',{'action':{'enum':['status','activate']}},['action'])
tool('status','Service version, catalog location, queue and processing state.',read=True)
tool('recipe_schema','Supported recipe ranges, defaults, presets and sync groups.',read=True)
tool('metadata_schema','Read supported IPTC fields, groups and value formats. These descriptive fields do not replace source EXIF capture time.',read=True)
from .develop_presets import FIELDS as DEVELOP_FIELDS
PRESET_ID=string(80)
PRESET_TOKEN=string(64)
tool('list_develop_presets','Page partial Develop presets and groups without loading recipe payloads. Shared storage is default; hidden groups are excluded unless requested.',{'offset':integer(),'group_offset':integer(),'search':{'type':'string','maxLength':200},'group_id':PRESET_ID,'favorites':BOOL,'include_hidden':BOOL},read=True)
tool('get_develop_preset','Read complete preset settings at the captured library revision.',{'preset_id':PRESET_ID,'expected_revision':PRESET_TOKEN},['preset_id','expected_revision'],read=True)
tool('save_develop_preset','Create or update a preset from explicitly selected settings of a captured photo. Does not edit photos. LUT assets are retained independently.',{'photo_id':ID,'expected_photo_revision':REV,'fields':array({'enum':list(DEVELOP_FIELDS)},128),'name':string(120),'group_name':string(120),'preset_id':PRESET_ID,'expected_revision':PRESET_TOKEN,'duplicate_policy':{'enum':['error','replace','duplicate']}},['photo_id','expected_photo_revision','fields','name','group_name','expected_revision'])
tool('develop_preset_action','Explicit preset favorite, duplicate, rename, move, delete, group visibility/name or storage preference change. Switching storage never moves presets.',{'action':{'enum':['favorite','duplicate','rename','move','delete','group_visibility','group_rename','storage']},'preset_id':PRESET_ID,'group_id':PRESET_ID,'name':string(120),'group_name':string(120),'favorite':BOOL,'visible':BOOL,'store_with_catalog':BOOL,'expected_revision':PRESET_TOKEN},['action','expected_revision'])
tool('apply_develop_preset','Apply only stored preset fields to up to sixty captured photo revisions in one transaction. Preserve metadata, catalog orientation, unchecked adjustments and queued exports.',{'preset_id':PRESET_ID,'expected_revision':PRESET_TOKEN,'targets':array(obj({'photo_id':ID,'expected_revision':REV},['photo_id','expected_revision']),60)},['preset_id','expected_revision','targets'])
tool('import_photos','Reference explicit local photos or directories; never copy or modify originals.',{'paths':array(PATH)},['paths'])
tool('prepare_import','Stage a durable Add import review for explicit files/folders. No photos enter the catalog until apply; originals stay in place.',{'paths':array(PATH),'include_subfolders':BOOL,'skip_duplicates':BOOL},['paths'])
tool('get_import','Read sixty import review summaries, selection totals and progress without metadata payloads.',{'plan_id':ID,'kind':{'enum':['all','new','duplicate','existing','error','selected']},'offset':integer(),'sort':{'enum':['name','captured','checked','type']},'descending':BOOL},read=True)
tool('scan_import','Advance one bounded directory or metadata scan page at the captured import review revision. Expensive file reads release the catalog lock.',{'plan_id':ID,'expected_revision':REV},['plan_id','expected_revision'])
tool('select_import_items','Check or uncheck eligible import items, optionally within a filter or explicit page IDs. Checking does not import.',{'plan_id':ID,'expected_revision':REV,'selected':BOOL,'item_ids':array(ID,60),'kind':{'enum':['all','new','duplicate']}},['plan_id','expected_revision','selected'])
tool('set_import_options','Change suspected-duplicate exclusion on a ready review, preserving manual checks.',{'plan_id':ID,'expected_revision':REV,'skip_duplicates':BOOL},['plan_id','expected_revision','skip_duplicates'])
tool('apply_import','Verify selected originals/sidecars and import checked references atomically with their descriptive metadata. Existing photographs are never overwritten. Read the plan after an uncertain reply; never replay.',{'plan_id':ID,'expected_revision':REV},['plan_id','expected_revision'])
tool('cancel_import','Cancel a pending import review. A completed catalog transaction remains applied; no originals are deleted.',{'plan_id':ID},['plan_id'])
tool('preview_import_item','Preview one scanned original without importing it. Bounded image worker and client generation cancellation are shared with normal previews.',{'plan_id':ID,'item_id':ID,'expected_revision':REV,'client_id':string(120),'generation':REV,'detail':BOOL},['plan_id','item_id','expected_revision','client_id','generation'],True)
IMPORT_PRESET={'anyOf':[obj({'preset_id':PRESET_ID,'expected_revision':PRESET_TOKEN},['preset_id','expected_revision']),{'type':'null'}]}
tool('get_import_processing','Read captured import preset names and additional keyword text without full preset payloads.',{'plan_id':ID},['plan_id'],True)
tool('set_import_processing','Capture Develop/metadata presets or additional keywords for a ready import. Later preset edits do not change the captured values. Null clears a preset; omitted settings are preserved.',{'plan_id':ID,'expected_revision':REV,'develop_preset':IMPORT_PRESET,'metadata_preset':IMPORT_PRESET,'keywords':{'type':'array','maxItems':100,'items':string()}},['plan_id','expected_revision'])
tool('list_photos','Read at most 60 summaries with SQL filters, collection membership and stable sorting. has_snapshots filters shared source-family presence; recipes are never loaded for filtering.',{'offset':integer(),'mode':{'enum':['all','stars','keepers','rejects','missing','duplicates','previous_import']},'search':{'type':'string','maxLength':200},'filters':FILTER_SCHEMA,'collection_id':ID,'sort':{'enum':list(SORTS)},'descending':BOOL},read=True)
tool('list_collections','Read at most 60 collections/sets, excluding Quick. Omit parent_id for flat compatibility; null selects roots, an ID selects children.',{'offset':integer(),'parent_id':OPTIONAL_ID},read=True)
TOOLS['list_photos']['inputSchema']['properties']['stacked']=BOOL
TOOLS['list_photos']['inputSchema']['properties'].update(folder_id=ID,include_subfolders=BOOL)
tool('library_state','Read compact folder, stack, keyword, previous-import and snapshot-presence revisions without photo payloads. snapshot_filter_revision advances on first/last snapshot transitions, not renames or settings updates.',read=True)
tool('orientation_state','Read the catalog orientation revision and latest independent rotate/flip undo action. Develop history is separate.',read=True)
tool('orient_photos','Rotate or flip up to sixty photos atomically at captured visual revisions. Orientation acts after Develop processing, survives Develop reset, and never changes recipes or originals.',{'targets':array(obj({'photo_id':ID,'expected_revision':REV},['photo_id','expected_revision']),60),'action':{'enum':['rotate_left','rotate_right','flip_horizontal','flip_vertical']}},['targets','action'])
tool('undo_orientation','Undo the latest catalog rotate/flip batch at the captured orientation-state revision and action ID. Preserves later Develop edits; any missing target rejects the whole undo.',{'action_id':ID,'expected_revision':REV},['action_id','expected_revision'])
KEYWORD_TARGET = obj({'photo_id':ID,'expected_metadata_revision':REV},['photo_id','expected_metadata_revision'])
METADATA_PRESET_TARGET=obj({'photo_id':ID,'expected_metadata_revision':REV,'expected_rating':integer(0,5)},['photo_id','expected_metadata_revision'])
tool('list_metadata_presets','Read thirty metadata preset summaries, editable field descriptors and shared/catalog storage state. Does not apply metadata.',{'offset':integer(),'search':{'type':'string','maxLength':200}},read=True)
tool('get_metadata_preset','Read explicitly saved metadata fields at a captured library/vocabulary token.',{'preset_id':PRESET_ID,'expected_revision':PRESET_TOKEN},['preset_id','expected_revision'],True)
tool('save_metadata_preset','Create or update explicitly checked metadata fields. Empty text clears checked fields when applying; keywords append. Saving never tags photos.',{'name':string(120),'patch':METADATA_PRESET_PATCH,'preset_id':PRESET_ID,'expected_revision':PRESET_TOKEN},['name','patch','expected_revision'])
tool('metadata_preset_action','Rename, duplicate, delete or switch metadata preset storage at a captured token. Switching storage never moves presets.',{'action':{'enum':['rename','duplicate','delete','storage']},'preset_id':PRESET_ID,'name':string(120),'store_with_catalog':BOOL,'expected_revision':PRESET_TOKEN},['action','expected_revision'])
tool('apply_metadata_preset','Apply saved metadata to up to sixty captured photos atomically; append keywords and preserve unchecked fields, recipes and originals. Presets including rating require expected_rating for every target.',{'preset_id':PRESET_ID,'expected_revision':PRESET_TOKEN,'targets':array(METADATA_PRESET_TARGET,60)},['preset_id','expected_revision','targets'])
tool('list_keywords','Read at most 60 keyword roots/children or search names/synonyms. Large rows set details_deferred with null path/synonyms and an abbreviated path_preview; read get_keyword before editing. Counts and selection states are direct assignments; keyword photo filters also include descendants.',{'parent_id':OPTIONAL_ID,'offset':integer(),'search':{'type':'string','maxLength':200},'photo_ids':array(ID,60)},read=True)
tool('get_keyword','Read complete keyword path, parent path, synonyms and export options at the captured keyword list revision. Deferred list fields are not empty values.',{'keyword_id':ID,'expected_revision':REV},['keyword_id','expected_revision'],True)
tool('import_keywords','Import a UTF-8 tab-indented text or keyword-options CSV dictionary, up to 64 MiB. Validate the entire file before one additive transaction. Existing tag identities, synonyms, policies and photo assignments are preserved.',{'path':PATH,'expected_revision':REV},['path','expected_revision'])
tool('export_keywords','Write a new keyword dictionary file without overwriting existing files. CSV preserves export/person options; text retains hierarchy, synonyms and Include on Export only. No photo assignments or originals are written.',{'path':PATH,'format':{'enum':['text','csv']},'expected_revision':REV},['path','format','expected_revision'])
SET_SLOTS={'type':'array','items':{'type':'string','maxLength':4096},'minItems':9,'maxItems':9}
SET_REV=string(64)
SHORTCUT_IDS={'type':'array','items':ID,'maxItems':100,'uniqueItems':True}
tool('get_keyword_shortcut','Read complete shortcut IDs and twenty full keyword paths. A shortcut retains keyword identity through rename; captured revisions protect paging and application.',{'offset':integer(),'expected_revision':SET_REV},read=True)
tool('set_keyword_shortcut','Replace the catalog keyword shortcut with stable IDs and optional new paths, up to one hundred keywords. Empty IDs clear it. Does not assign photos.',{'keyword_ids':SHORTCUT_IDS,'keyword_additions':{'type':'array','items':string(4096),'maxItems':100},'expected_revision':SET_REV},['keyword_ids','expected_revision'])
tool('paint_library','Apply one keyword shortcut, rating, flag or label to at most sixty captured photos in a single transaction. Keywords require the shortcut revision; erase removes only those tags. Other modes use an explicit value, including 0/none to clear.',{'targets':array(KEYWORD_TARGET,60),'kind':{'enum':['keywords','rating','flag','label']},'value':{'anyOf':[integer(-1,5),{'enum':list(COLORS)}]},'erase':BOOL,'expected_shortcut_revision':SET_REV},['targets','kind'])
tool('list_keyword_sets','Read thirty preset names and the selected nine slots. Recent Keywords uses catalog identities. Shared preset storage is initialized on first use.',{'offset':integer()},read=True)
tool('get_keyword_set','Preview any nine-slot preset and thirty names at a captured state revision without selecting it. Recent slots include stable keyword IDs; custom slots remain text. Browsing never creates vocabulary or changes the active preset.',{'set_id':string(36),'expected_revision':SET_REV,'offset':integer()},['set_id','expected_revision'],True)
tool('save_keyword_set','Create or update a named nine-slot keyword set at the captured state token. Slots are text; saving never creates or assigns keywords.',{'name':string(120),'slots':SET_SLOTS,'set_id':string(36),'expected_revision':SET_REV},['name','slots','expected_revision'])
tool('keyword_set_action','Select or delete a keyword set, or switch shared versus catalog-local storage without copying existing presets. Recent Keywords cannot be deleted.',{'action':{'enum':['select','delete','storage']},'set_id':string(36),'store_with_catalog':BOOL,'expected_revision':SET_REV},['action','expected_revision'])
tool('apply_keyword_set','Add one selected keyword-set slot to up to sixty photos atomically at captured preset and metadata revisions. Optional draft slots are transient; Recent Keywords resolves by stable identity.',{'slot':integer(1,9),'draft_slots':SET_SLOTS,'targets':array(KEYWORD_TARGET,60),'expected_revision':SET_REV},['slot','targets','expected_revision'])
tool('save_keyword','Create, rename or move a keyword with up to 30 synonyms. Requires the keyword list revision; ancestor paths of assigned photos also invalidate their metadata revisions.',{'name':string(120),'parent_id':OPTIONAL_ID,'keyword_id':ID,'expected_revision':REV,'synonyms':{'type':'array','items':string(120),'maxItems':30}},['name','expected_revision'])
TOOLS['save_keyword']['inputSchema']['properties']['targets']=array(KEYWORD_TARGET,60)
TOOLS['save_keyword']['inputSchema']['properties']['is_person']=BOOL
tool('delete_keyword','Delete one keyword subtree and its photo assignments atomically; preserve originals and recipes.',{'keyword_id':ID,'expected_revision':REV},['keyword_id','expected_revision'])
TOOLS['delete_keyword']['annotations']['destructiveHint']=True
tool('keyword_membership','Add/remove a keyword on up to 60 photos without replacing other tags. Requires both keyword list and photo metadata revisions.',{'keyword_id':ID,'expected_revision':REV,'targets':array(KEYWORD_TARGET,60),'action':{'enum':['add','remove']}},['keyword_id','expected_revision','targets','action'])
tool('list_folders','Read at most 60 catalog folder roots or children, with direct/descendant photo counts. Search/favorite/color filters return a flat list; never scan the filesystem tree.',{'parent_id':OPTIONAL_ID,'offset':integer(),'search':{'type':'string','maxLength':200},'favorites':BOOL,'color_label':{'enum':list(COLORS)}},read=True)
tool('get_folder','Read exactly one folder or the folder containing a photo, including ancestors and navigation offsets. No directory writes.',{'folder_id':ID,'photo_id':ID},read=True)
tool('edit_folder','Change catalog-only folder favorite/color label with optimistic metadata revision.',{'folder_id':ID,'expected_revision':REV,'patch':obj({'favorite':BOOL,'color_label':{'enum':list(COLORS)}})},['folder_id','expected_revision','patch'])
tool('set_folder_visibility','Show a root folder parent or hide an empty parent in favor of its children. Changes catalog presentation only; requires the folder tree revision.',{'folder_id':ID,'expected_revision':REV,'action':{'enum':['show_parent','hide_parent']}},['folder_id','expected_revision','action'])
tool('prepare_folder_relocation','Stage a missing folder subtree at a chosen existing directory. Preserves original files; only one active relocation plan per catalog.',{'folder_id':ID,'destination':PATH,'expected_revision':REV},['folder_id','destination','expected_revision'])
tool('get_folder_relocation','Read a relocation receipt and at most 60 proposed paths. Omit plan_id for the latest plan; issues_only defaults true.',{'plan_id':ID,'offset':integer(),'issues_only':BOOL},read=True)
tool('scan_folder_relocation','Check at most 60 staged source families, hashing only indexed originals. No catalog lock is held during file reads; continue while state is planning.',{'plan_id':ID,'expected_revision':REV},['plan_id','expected_revision'])
tool('apply_folder_relocation','Recheck staged file identities and atomically relink the complete folder tree, variants, stacks and inactive export sources. Conflicting original paths block application.',{'plan_id':ID,'expected_revision':REV},['plan_id','expected_revision'])
tool('cancel_folder_relocation','Cancel staged verification and discard its temporary mapping; never undo an already committed relocation.',{'plan_id':ID},['plan_id'])
tool('prepare_folder_sync','Stage synchronization of an existing folder and all descendants. Originals are read-only; metadata is optional and removal requires an explicit apply option.',{'folder_id':ID,'expected_revision':REV,'scan_metadata':BOOL},['folder_id','expected_revision','scan_metadata'])
tool('get_folder_sync','Read a saved synchronization plan and at most 60 summaries. Large patches have metadata_deferred=true; use get_folder_sync_metadata for complete values. Omit plan_id for the latest plan.',{'plan_id':ID,'offset':integer(),'kind':{'enum':['all','changes','new','missing','updated','error','unchanged']}},read=True)
tool('get_folder_sync_metadata','Read complete scanned fields and up to 20 keyword paths for one item in a captured synchronization revision. No catalog or original writes.',{'plan_id':ID,'item_id':ID,'expected_revision':REV,'offset':integer()},['plan_id','item_id','expected_revision'],read=True)
tool('scan_folder_sync','Read at most 256 directory entries or metadata for 60 originals per request; continue while planning. Filesystem reads release the catalog lock.',{'plan_id':ID,'expected_revision':REV},['plan_id','expected_revision'])
tool('select_folder_sync_items','Select/deselect new, missing or updated files in a ready plan. Choose up to 60 item_ids, a folder subtree, or all items of one kind.',{'plan_id':ID,'expected_revision':REV,'selected':BOOL,'kind':{'enum':['new','missing','updated']},'item_ids':array(ID,60),'folder':PATH},['plan_id','expected_revision','selected'])
tool('apply_folder_sync','Revalidate and apply the reviewed plan atomically. Import in place, optionally remove missing originals and their variants from the catalog, and optionally read supported descriptive metadata onto masters.',{'plan_id':ID,'expected_revision':REV,'import_new':BOOL,'remove_missing':BOOL,'read_metadata':BOOL},['plan_id','expected_revision'])
TOOLS['apply_folder_sync']['annotations']['destructiveHint']=True
tool('cancel_folder_sync','Discard an unfinished synchronization plan; a completed transaction remains applied.',{'plan_id':ID},['plan_id'])
tool('stack_state','Read the current stack revision for optimistic grouping and visibility changes.',read=True)
AUTO_SOURCE={'folder':PATH,'collection_id':ID}
AUTO_TIME={**AUTO_SOURCE,'seconds':{'type':'number','minimum':0,'maximum':3600}}
tool('preview_auto_stack','Preview capture-time groups for exactly one folder or regular/Quick collection, independent of selection and filters. Returns a fingerprint and at most 20 example groups.',AUTO_TIME,['seconds'],True)
tool('apply_auto_stack','Replace stack organization in the previewed source only if its capture times, membership and stacks still match the token. Originals and recipes are unchanged.',{**AUTO_TIME,'token':string(64)},['seconds','token'])
tool('refresh_capture_times','Read only bounded EXIF headers for at most 60 physical sources in one folder or collection. Continue with after_source_id until done; no hashing or pixels.',{**AUTO_SOURCE,'after_source_id':integer()})
tool('set_stack_visibility','Expand/collapse all stacks in the captured source, independent of photo selection or metadata filters. folder includes descendants unless include_subfolders is false; omit source for all folder stacks.',{'collapsed':BOOL,'expected_revision':REV,'collection_id':ID,'folder':PATH},['collapsed','expected_revision'])
TOOLS['set_stack_visibility']['inputSchema']['properties']['include_subfolders']=BOOL
tool('stack_photos','Change source-scoped stacks atomically. Ordered photo_ids define initial order; active_id becomes the new cover. Split moves a selected subset from an expanded stack; singletons become unstacked. Hidden members are never implicitly selected.',{'action':{'enum':['group','split','unstack','remove','expand','collapse','toggle','top','up','down']},'photo_ids':array(ID,60),'expected_revision':REV,'collection_id':ID,'active_id':ID},['action','photo_ids','expected_revision'])
tool('get_collection','Read one collection and its bounded ancestor path.',{'collection_id':ID},['collection_id'],True)
tool('save_collection','Create or edit a regular/smart collection or set; parent_id moves it, null moves to root. Updates require its revision; originals are unchanged.',{'collection_id':ID,'expected_revision':REV,'name':string(120),'kind':{'enum':['regular','smart','set']},'parent_id':OPTIONAL_ID,'photo_ids':array(ID,60),'rules':FILTER_SCHEMA,'match':{'enum':['all','any']}},['name','kind'])
tool('collection_membership','Add/remove photos in a regular or Quick Collection atomically; never removes originals or catalog photos.',{'collection_id':ID,'expected_revision':REV,'photo_ids':array(ID,60),'action':{'enum':['add','remove']}},['collection_id','expected_revision','photo_ids','action'])
tool('delete_collection','Delete a collection or an entire set subtree and its memberships; preserve all photos and originals. Ancestor revisions cover descendant changes.',{'collection_id':ID,'expected_revision':REV},['collection_id','expected_revision'])
tool('duplicate_collection','Atomically duplicate a collection or a subtree of up to 1000 collections, preserving rules and memberships without copying originals.',{'collection_id':ID,'expected_revision':REV,'name':string(120)},['collection_id','expected_revision','name'])
tool('collection_state','Read the durable Quick and target collections; optionally query target membership for a bounded visible page.',{'photo_ids':array(ID,60)},read=True)
tool('set_target_collection','Choose a regular target collection; null resets to Quick. Requires the current state revision.',{'collection_id':OPTIONAL_ID,'expected_revision':REV},['expected_revision'])
tool('target_membership','Add/remove photos only if the captured target and collection revisions still match.',{'collection_id':ID,'expected_state_revision':REV,'expected_revision':REV,'photo_ids':array(ID,60),'action':{'enum':['add','remove']}},['collection_id','expected_state_revision','expected_revision','photo_ids','action'])
tool('quick_collection','Clear Quick or atomically save it as a regular collection, optionally clearing afterward.',{'expected_revision':REV,'action':{'enum':['clear','save']},'name':string(120),'clear_after':BOOL,'parent_id':OPTIONAL_ID},['expected_revision','action'])
tool('edit_metadata','Atomically update catalog-only descriptive metadata. Keywords replace the current set. Recipe revisions remain unchanged.',{'targets':array(obj({'photo_id':ID,'expected_metadata_revision':REV},['photo_id','expected_metadata_revision']),60),'patch':obj({'copy_name':{'type':'string','maxLength':120},'title':{'type':'string','maxLength':500},'caption':{'type':'string','maxLength':5000},'copyright':{'type':'string','maxLength':500},'color_label':{'enum':list(COLORS)},'keywords':{'type':'array','items':string(120),'maxItems':100}})},['targets','patch'])
TOOLS['edit_metadata']['inputSchema']['properties']['patch']['properties']['keywords']['items']=string(4096)
TOOLS['edit_metadata']['inputSchema']['properties']['patch']['properties']['iptc']=IPTC_SCHEMA
COPY_TARGET={'photo_id':ID,'expected_revision':REV,'expected_metadata_revision':REV}
for policy in ('include_export','export_containing','export_synonyms'):
    TOOLS['save_keyword']['inputSchema']['properties'][policy]=BOOL
tool('preview_export_metadata','Preview supported catalog metadata and resolved export keywords without changing originals. Pages contain up to 60 keywords or hierarchy paths; policies and synonyms are applied.',{'photo_id':ID,'kind':{'enum':['keywords','hierarchy']},'offset':integer(),'metadata':{'enum':['none','copyright','catalog']},'keyword_hierarchy':BOOL},['photo_id'],True)
COPY_REMOVE={**COPY_TARGET,'expected_source_revision':REV}
tool('create_virtual_copies','Atomically create up to 60 independent catalog variants sharing their original files. Optionally add to a captured regular/Quick collection.',{'targets':array(obj(COPY_TARGET,COPY_TARGET),60),'collection_id':ID,'expected_collection_revision':REV},['targets'])
tool('remove_virtual_copies','Remove only virtual copies and their private history/memberships; preserve originals, shared snapshots and queued export snapshots.',{'targets':array(obj(COPY_REMOVE,COPY_REMOVE),60)},['targets'])
TOOLS['remove_virtual_copies']['annotations']['destructiveHint']=True
tool('set_copy_as_master','Promote a virtual copy and demote the old master without changing IDs, recipes, collections or originals.',COPY_REMOVE,COPY_REMOVE)
tool('get_photo','Read recipe, metadata and revisions. keyword_ids is complete; keywords_deferred=true means display paths are omitted, not unassigned. Read those paths with get_photo_keywords.',{'photo_id':ID},['photo_id'],True)
tool('get_photo_keywords','Read twenty complete assigned keyword paths at a captured photo metadata revision. Photo details always contain complete keyword_ids; large display paths are marked keywords_deferred.',{'photo_id':ID,'expected_metadata_revision':REV,'offset':integer()},['photo_id','expected_metadata_revision'],True)
tool('keyword_choices','Read twenty complete keyword paths for an assignment picker. Search names/synonyms or supply up to 100 explicit IDs; empty IDs select nothing.',{'search':{'type':'string','maxLength':200},'keyword_ids':{'type':'array','items':ID,'maxItems':100,'uniqueItems':True},'offset':integer()},read=True)
TOOLS['edit_metadata']['inputSchema']['properties']['patch']['properties'].update(
    keyword_ids={'type':'array','items':ID,'maxItems':100,'uniqueItems':True},
    keyword_additions={'type':'array','items':string(4096),'maxItems':100})
TOOLS['edit_metadata']['description']='Atomically update catalog metadata at captured revisions. Replace keywords with text keywords OR complete keyword_ids plus optional new keyword_additions paths. Never mix both replacement forms. Omitted fields stay unchanged; originals and recipe revisions are preserved.'
tool('edit_photo','Merge a partial recipe using expected_revision; stale revisions fail without changes.',{'photo_id':ID,'expected_revision':REV,'patch':PATCH},['photo_id','expected_revision','patch'])
tool('undo_photo','Undo the last edit only if the revision is current.',{'photo_id':ID,'expected_revision':REV},['photo_id','expected_revision'])
tool('redo_photo','Move forward one retained Develop history step at the captured photo revision.',{'photo_id':ID,'expected_revision':REV},['photo_id','expected_revision'])
tool('list_history','Read at most sixty Develop history summaries, newest first, without recipe payloads. Step zero is the initial retained state. before_id pages toward older steps.',{'photo_id':ID,'expected_revision':REV,'before_id':REV},['photo_id','expected_revision'],True)
tool('select_history','Return to a retained Develop state without deleting later states. A subsequent edit replaces the future branch.',{'photo_id':ID,'expected_revision':REV,'step_id':REV},['photo_id','expected_revision','step_id'])
tool('rename_history','Rename one history state without changing pixels. Invalidates captured photo revisions.',{'photo_id':ID,'expected_revision':REV,'step_id':REV,'name':string(120)},['photo_id','expected_revision','step_id','name'])
tool('clear_history','Discard this photo\'s Develop timeline while keeping its current recipe as the new baseline. Cannot be undone; snapshots and exports are preserved.',{'photo_id':ID,'expected_revision':REV},['photo_id','expected_revision'])
TOOLS['clear_history']['annotations']['destructiveHint']=True
tool('before_after','Copy a history state, a revision-checked named snapshot or current After settings to persistent Before, copy Before to After, or swap both atomically. Before-only changes retain Develop history/redo; After changes create one ordinary history step. Snapshot copying requires version_id and expected_version_revision.',{'photo_id':ID,'expected_revision':REV,'action':{'enum':['history_to_before','after_to_before','before_to_after','swap','snapshot_to_before']},'step_id':REV,'version_id':ID,'expected_version_revision':REV},['photo_id','expected_revision','action'])
tool('rate_photo','Set rating 0–5 and/or pick flag (-1 reject, 0 neutral, 1 pick).',{'photo_id':ID,'rating':integer(0,5),'flag':{'enum':[-1,0,1]}},['photo_id'])
tool('rate_photos','Atomically set ratings and/or pick flags on a bounded selection; leaves recipes and metadata revisions unchanged.',{'photo_ids':array(ID,60),'rating':integer(0,5),'flag':{'enum':[-1,0,1]}},['photo_ids'])
tool('preview_photo','Render an sRGB preview or full-resolution viewport. Set include_before=false to skip baseline processing; max_edge bounds fitted previews only.',{'photo_id':ID,'client_id':string(128),'generation':integer(),'include_before':BOOL,'max_edge':integer(128,1680),'detail':obj({'cx':{'type':'number','minimum':0,'maximum':1},'cy':{'type':'number','minimum':0,'maximum':1},'width':integer(1,2048),'height':integer(1,1536)}),'display':obj({'gamut':BOOL,'proof_path':PATH,'proof_sha':string(64)})},['photo_id'],True)
CURVE_POINT={'type':'array','items':{'type':'number','minimum':0,'maximum':1},'minItems':2,'maxItems':2}
CURVE_PATCH=obj({key:{'type':'array','items':CURVE_POINT,'minItems':2,'maxItems':16} for key in (*POINT_CURVE_FIELDS,'curve_points')})
CURVE_PATCH['properties'].update({key:{'type':'number','minimum':-100,'maximum':100} for key in PARAMETRIC_FIELDS})
CURVE_PATCH['properties']['parametric_splits']={'type':'array','items':{'type':'number','minimum':.01,'maximum':.99},'minItems':3,'maxItems':3}
CURVE_PATCH['minProperties']=1
TOOLS['preview_photo']['inputSchema']['properties'].update(curve_patch=CURVE_PATCH,expected_revision=REV)
TOOLS['preview_photo']['description']+=' expected_revision also binds ordinary previews before and after processing; a changed photo fails visibly without returning stale pixels.'
TOOLS['preview_photo']['description']+=' Completed previews may be reused after bounded artifact integrity checks; preview_cache_hit and worker_spawned distinguish reuse from processing.'
TOOLS['preview_photo']['inputSchema']['properties']['include_curve_tones']=BOOL
TOOLS['preview_photo']['inputSchema']['properties']['include_color_readouts']=BOOL
TOOLS['preview_photo']['description']+=' include_color_readouts returns bounded float32 SDR Develop RGB percent/CIELAB D50 maps before display proofing, with cropped full-image dimensions and optional Before maps.'
TOOLS['preview_photo']['description']+=' include_curve_tones returns a bounded, geometry-aligned pre-parametric input-tone map for targeted adjustment.'
TOOLS['preview_photo']['inputSchema']['dependentRequired']={'curve_patch':['expected_revision']}
TOOLS['preview_photo']['description']+=' curve_patch previews temporary point or parametric curves at expected_revision without saving edits or history.'
MIXER_PATCH=obj({key:{'type':'number','minimum':LIMITS[key][0],'maximum':LIMITS[key][1]} for key in (*MIXER_FIELDS,*BW_FIELDS)})
MIXER_PATCH['minProperties']=1
TOOLS['preview_photo']['inputSchema']['properties'].update(mixer_patch=MIXER_PATCH,mixer_target={'enum':['hsl','bw']})
TOOLS['preview_photo']['inputSchema']['dependentRequired']['mixer_patch']=['expected_revision']
TOOLS['preview_photo']['inputSchema']['not']={'required':['curve_patch','mixer_patch']}
TOOLS['preview_photo']['description']+=' mixer_patch previews temporary HSL/B&W values at expected_revision, separately from curve_patch. mixer_target returns aligned sparse band weights before HSL or B&W mixing.'
tool('cancel_preview','Invalidate older preview generations for one client and stop its older running preview/thumbnail. Never cancels exports or another client.',{'client_id':string(128),'generation':integer()},['client_id','generation'])
tool('photo_summaries','Read existing photo summaries for at most 60 IDs without recipe or EXIF payloads.',{'photo_ids':array(ID,60)},['photo_ids'],True)
tool('thumbnail','Create/read a source thumbnail (default) or a developed recipe-aware 320-pixel thumbnail.',{'photo_id':ID,'kind':{'enum':['source','developed']},'client_id':string(128),'generation':integer()},['photo_id'],True)
tool('cached_thumbnails','Read completed source (default) or developed thumbnail paths for up to 60 photos without image workers. Developed entries include recipe revisions.',{'photo_ids':array(ID,60),'kind':{'enum':['source','developed']}},['photo_ids'],True)
tool('enqueue_exports','Durably enqueue immutable recipe snapshots. Reusing request_key with the same arguments returns original jobs; different arguments fail.',{'photo_ids':array(ID),'destination':PATH,'format':{'enum':['tiff16','jpeg']},'options':obj({'space':{'enum':['srgb','adobe','p3','prophoto']},'max_edge':integer(0,16000),'quality':integer(1,100),'output_sharpen':{'type':'number','minimum':0,'maximum':150},'name':string(120),'priority':integer(0,9)}),'request_key':string(128)},['photo_ids','destination','format','request_key'])
tool('get_job','Read a specific durable export receipt, including its recipe snapshot.',{'job_id':ID},['job_id'],True)
TOOLS['enqueue_exports']['inputSchema']['properties']['options']['properties'].update({'metadata':{'enum':['none','copyright','catalog']},'keyword_hierarchy':BOOL})
tool('list_jobs','Read the latest 60 export jobs and aggregate queue counts.',read=True)
tool('queue_control','Pause after the current export, resume, cancel, or retry failed/interrupted exports. Cancelled exports require explicit retry_cancelled.',{'action':{'enum':['pause','resume','cancel','retry','retry_cancelled']},'job_id':ID},['action'])
tool('save_version','Create a named snapshot shared by all variants. Pass expected_revision to capture current settings safely; optional step_id copies a retained history state without selecting it and requires that revision. Duplicate names are rejected, never overwritten.',{'photo_id':ID,'name':string(120),'expected_revision':REV,'step_id':REV},['photo_id','name'])
tool('list_versions','Page up to 60 snapshot summaries alphabetically. after_id requires expected_snapshots_revision; known_revision returns a compact unchanged receipt when the family list is unchanged. Recipes are never included.',{'photo_id':ID,'after_id':ID,'expected_snapshots_revision':REV,'known_revision':REV},['photo_id'],True)
tool('restore_version','Restore a snapshot with photo conflict detection and undo history. Pass expected_version_revision to reject a snapshot changed since listing; omission reads its latest value for older clients.',{'photo_id':ID,'version_id':ID,'expected_revision':REV,'expected_version_revision':REV},['photo_id','version_id','expected_revision'])
SNAPSHOT_TARGET={'photo_id':ID,'version_id':ID,'expected_version_revision':REV}
tool('rename_version','Rename a shared snapshot without changing any recipe. Checks the captured snapshot revision.',{**SNAPSHOT_TARGET,'name':string(120)},[*SNAPSHOT_TARGET,'name'])
tool('update_version','Replace one shared snapshot with the current photo settings. Requires both captured revisions; leaves live edits, Before, history and exports unchanged. Previous snapshot settings cannot be recovered by Develop undo.',{**SNAPSHOT_TARGET,'expected_revision':REV},[*SNAPSHOT_TARGET,'expected_revision'])
tool('delete_version','Delete a shared snapshot for the master and all virtual copies. Requires the captured snapshot revision; preserves originals, live edits, Before, history and exports. Cannot be undone.',SNAPSHOT_TARGET,SNAPSHOT_TARGET)
TOOLS['update_version']['annotations']['destructiveHint']=True
TOOLS['delete_version']['annotations']['destructiveHint']=True
tool('sync_photos','Copy selected parameter groups atomically; every target requires its current revision.',{'source_id':ID,'targets':array(obj({'photo_id':ID,'expected_revision':REV},['photo_id','expected_revision']),60),'groups':array({'enum':list(SYNC_GROUPS)},len(SYNC_GROUPS))},['source_id','targets','groups'])
tool('index_library','Hash originals read-only, detect duplicates, missing files and EXIF bursts.')
tool('relink_photo','Relink a missing original; checks a known content fingerprint.',{'photo_id':ID,'path':PATH},['photo_id','path'])
tool('backup_catalog','Write a new SQLite backup and asset directory; never overwrite.',{'path':PATH},['path'])
tool('restore_catalog','Restore a backup to a new empty catalog directory; exports remain interrupted.',{'path':PATH,'destination':PATH},['path','destination'])
tool('import_asset','Validate a LUT, ICC proof profile, or camera calibration profile.',{'path':PATH,'kind':{'enum':['lut','icc','profile']}},['path','kind'])
tool('save_recipe','Save a portable recipe bundle to a new file.',{'photo_id':ID,'path':PATH},['photo_id','path'])
tool('load_recipe','Load a recipe bundle with conflict detection.',{'photo_id':ID,'path':PATH,'expected_revision':REV},['photo_id','path','expected_revision'])
RECT={'type':'array','items':{'type':'number','minimum':0,'maximum':1},'minItems':4,'maxItems':4}
tool('calibrate_camera','Fit a camera-bound 24-patch profile against an explicit reference. Result is not independent Nikon accuracy evidence.',{'photo_id':ID,'reference':PATH,'source_rect':RECT,'reference_rect':RECT,'name':string(120),'lighting':string(256)},['photo_id','reference','source_rect','reference_rect','name','lighting'])
tool('settings','Read or update import navigation, memory budget and compute backend: auto (Metal with CPU fallback), cpu, or metal (GPU failures reported). Includes last processing timings.',{'select_previous_import':BOOL,'budget_mb':integer(256,32768),'compute_backend':{'enum':['auto','cpu','metal']}})
